//! The call family (SPEC §8.6 `callee` / `caller` / `call_edge`):
//! resolved call edges with dispatch classification.
//!
//! Directions differ in shape on purpose (SPEC §6.2):
//! - [`raql_callees`] is a Salsa-tracked query — body-local work with
//!   narrow dependencies; caches well.
//! - [`callers_of`] is an untracked function over the concrete snapshot —
//!   reference search is inherently wide, and ide-db's `usages` API is
//!   typed over concrete `RootDatabase`, which a tracked body (dyn-typed)
//!   cannot name. Tracking it is an optimization to revisit with evidence
//!   (SPEC §6.2, §18).

use std::sync::Arc;
use std::sync::atomic::{AtomicU64, Ordering};

use hir::db::HirDatabase;
use hir::{Semantics, SemanticsImpl};
use ide_db::RootDatabase;
use ide_db::defs::Definition;
use syntax::{AstNode, ast};

use crate::snapshot::with_attached_dyn;

/// Dispatch classification at one callsite (`DispatchKind` in `std.raql`).
#[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub enum DispatchKind {
    /// Statically dispatched call (free fn, inherent method, UFCS path).
    Direct,
    /// Trait-method call, statically resolved (generic or concrete receiver).
    ThroughTrait,
    /// Trait-object dispatch (`dyn Trait` receiver, incl. through autoderef).
    Dyn,
    /// Callee is a closure (callee side only; no `Def` identity, SPEC §6.3).
    Closure,
    /// Callee is a fn pointer / `impl Fn` value (callee side only).
    FnPointer,
}

impl DispatchKind {
    /// The catalog enum-tag spelling (matches `std.raql`'s `DispatchKind`).
    pub fn tag(self) -> &'static str {
        match self {
            DispatchKind::Direct => "DIRECT",
            DispatchKind::ThroughTrait => "THROUGH_TRAIT",
            DispatchKind::Dyn => "DYN",
            DispatchKind::Closure => "CLOSURE",
            DispatchKind::FnPointer => "FN_POINTER",
        }
    }
}

/// One resolved call edge endpoint inside a function body.
///
/// `peer` is the *other* end of the edge: the callee in [`raql_callees`]
/// rows, the caller in [`callers_of`] rows. Values are snapshot-scoped
/// (SPEC §4.1).
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub struct CallSite {
    pub peer: hir::Function,
    /// Primary-source range of the callsite (macro-aware).
    pub range: ide_db::FileRange,
    pub dispatch: DispatchKind,
}

static RAQL_CALLEES_EXECUTIONS: AtomicU64 = AtomicU64::new(0);

/// Number of times the `raql_callees` query body actually executed (i.e.
/// was not answered from Salsa's memo table). Observability for the spike
/// gates G2/G3 and incrementality tests (SPEC §16.3); not semantic state.
pub fn raql_callees_execution_count() -> u64 {
    RAQL_CALLEES_EXECUTIONS.load(Ordering::Relaxed)
}

/// Resolved outgoing call edges of one function body (SPEC §8.6 `callee`).
///
/// Completeness `ra_resolved`, caveat `unresolved_callsites_absent`:
/// callsites whose callee RA cannot resolve to a `hir::Function` (closures,
/// fn pointers, tuple-struct/variant constructors, resolution failures) are
/// absent, never approximated. Calls generated by macro expansion inside
/// the body are also currently absent (raw-AST body walk, matching RA's own
/// `outgoing_calls`).
pub fn raql_callees(db: &dyn HirDatabase, f: hir::Function) -> Arc<[CallSite]> {
    #[salsa::interned]
    struct InternedFunction {
        #[returns(copy)]
        f: hir::Function,
    }

    #[salsa::tracked(returns(ref))]
    fn raql_callees<'db>(
        db: &'db dyn HirDatabase,
        f: InternedFunction<'db>,
    ) -> Arc<[CallSite]> {
        RAQL_CALLEES_EXECUTIONS.fetch_add(1, Ordering::Relaxed);
        // Salsa may (re-)execute this body from any caller's verification
        // stack, where the TLS slot may be empty; type resolution needs it.
        with_attached_dyn(db, || compute_callees(db, f.f(db)))
    }

    raql_callees(db, InternedFunction::new(db, f)).clone()
}

/// Body of the `raql_callees` query. Adapted from rust-analyzer's
/// `ide::call_hierarchy::outgoing_calls` (identity-lossy, position-based),
/// keyed by and returning `hir` handles instead (SPEC §6.3).
fn compute_callees(db: &dyn HirDatabase, f: hir::Function) -> Arc<[CallSite]> {
    let sema = Semantics::new_dyn(db);
    let Some(source) = sema.source(f) else {
        return Arc::from([]);
    };
    let Some(body) = source.value.body() else {
        return Arc::from([]);
    };

    let mut sites = Vec::new();
    for node in body.syntax().descendants() {
        let Some(callable) = ast::CallableExpr::cast(node) else {
            continue;
        };
        let site = match &callable {
            ast::CallableExpr::Call(call) => call.expr().and_then(|expr| {
                let ty = sema.type_of_expr(&expr)?;
                match ty.original.as_callable(db)?.kind() {
                    hir::CallableKind::Function(callee) => Some(CallSite {
                        peer: callee,
                        dispatch: DispatchKind::Direct,
                        range: sema.original_range(expr.syntax()).into_file_id(db),
                    }),
                    // Closures, fn pointers, tuple-struct/variant
                    // constructors: no honest `hir::Function` identity —
                    // absent (`unresolved_callsites_absent`).
                    _ => None,
                }
            }),
            ast::CallableExpr::MethodCall(method_call) => {
                sema.resolve_method_call(method_call).and_then(|callee| {
                    let name_ref = method_call.name_ref()?;
                    Some(CallSite {
                        peer: callee,
                        dispatch: method_dispatch(&sema, method_call, callee),
                        range: sema.original_range(name_ref.syntax()).into_file_id(db),
                    })
                })
            }
        };
        sites.extend(site);
    }
    sites.into()
}

/// Resolved incoming call edges of one function (SPEC §8.6 `caller`):
/// reference search plus one ancestor-walk classification per site.
///
/// Completeness `ra_resolved`, caveats: references RA cannot resolve are
/// absent; non-call references (the fn passed as a value) are absent;
/// callsites inside closures are attributed to the enclosing named function
/// (matching RA's own call hierarchy — closures have no `Def` identity,
/// SPEC §6.3).
///
/// Untracked on purpose — see the module docs.
pub fn callers_of(db: &RootDatabase, f: hir::Function) -> Vec<CallSite> {
    let sema = Semantics::new(db);
    let mut sites = Vec::new();
    for (_file_id, references) in Definition::Function(f).usages(&sema).all() {
        for reference in &references {
            let Some(name_ref) = reference.name.as_name_ref() else {
                continue;
            };
            let Some(site) = classify_incoming(&sema, name_ref) else {
                continue;
            };
            sites.push(site);
        }
    }
    sites
}

/// One ancestor walk per incoming reference: find the callsite expression
/// and the enclosing named function, classify dispatch at the callsite.
/// Ported from the previous host's `call_lookup` (minus its synthetic
/// closure/fn-pointer defs — deleted concepts).
fn classify_incoming(
    sema: &Semantics<'_, RootDatabase>,
    name_ref: &ast::NameRef,
) -> Option<CallSite> {
    let mut callable = None::<ast::CallableExpr>;
    for ancestor in sema.ancestors_with_macros(name_ref.syntax().clone()) {
        if callable.is_none() {
            callable = ast::CallableExpr::cast(ancestor.clone());
        }
        if let Some(ast_fn) = ast::Fn::cast(ancestor) {
            let caller = sema.to_def(&ast_fn)?;
            let (range_node, dispatch) = match callable? {
                ast::CallableExpr::MethodCall(method_call) => {
                    let callee = sema.resolve_method_call(&method_call)?;
                    let name = method_call.name_ref()?;
                    (name.syntax().clone(), method_dispatch(sema, &method_call, callee))
                }
                ast::CallableExpr::Call(call) => {
                    (call.expr()?.syntax().clone(), DispatchKind::Direct)
                }
            };
            return Some(CallSite {
                peer: caller,
                dispatch,
                range: sema.original_range(&range_node).into_file_id(sema.db),
            });
        }
    }
    // Reference outside any named function body (e.g. in a const default,
    // or a non-call mention): no call edge.
    None
}

/// Dispatch classification of a method call (ported from the previous
/// host): `dyn Trait` receiver (directly or through autoderef) → `Dyn`;
/// trait-declared method → `ThroughTrait`; inherent method → `Direct`.
fn method_dispatch(
    sema: &SemanticsImpl<'_>,
    method_call: &ast::MethodCallExpr,
    callee: hir::Function,
) -> DispatchKind {
    let db = sema.db;
    let receiver_is_dyn = method_call
        .receiver()
        .and_then(|receiver| sema.type_of_expr(&receiver))
        .map(|info| {
            let receiver_ty = info.original;
            receiver_ty.as_dyn_trait().is_some()
                || receiver_ty
                    .autoderef(db)
                    .any(|candidate| candidate.as_dyn_trait().is_some())
        })
        .unwrap_or(false);
    if receiver_is_dyn {
        return DispatchKind::Dyn;
    }
    if hir::AssocItem::Function(callee)
        .container_or_implemented_trait(db)
        .is_some()
    {
        return DispatchKind::ThroughTrait;
    }
    DispatchKind::Direct
}
