[package]
name = "raql-cli"
version = "0.0.0"
edition = "2024"

[lib]
doctest = false

[dependencies]
raql-syntax = { path = "../raql-syntax" }
raql-compiler = { path = "../raql-compiler" }
raql-daemon = { path = "../raql-daemon" }
raql-protocol = { path = "../raql-protocol" }

clap.workspace = true
camino.workspace = true
