[package]
name = "raql-cli"
version = "0.0.0"
edition = "2024"

[dependencies]
raql-syntax = { path = "../raql-syntax" }
raql-compiler = { path = "../raql-compiler" }
raql-engine = { path = "../raql-engine" }
raql-host-ra = { path = "../raql-host-ra" }

clap.workspace = true
miette.workspace = true
thiserror.workspace = true
